# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Helpdesk.Repo.insert!(%Helpdesk.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

seinfeld_names = [
  "Jerry Seinfeld",
  "George Costanza",
  "Elaine Benes",
  "Cosmo Kramer",
  "Newman",
  "Frank Costanza",
  "Estelle Costanza",
  "Susan Ross",
  "David Puddy",
  "Morty Seinfeld",
  "Helen Seinfeld",
  "Jackie Chiles",
  "J. Peterman",
  "Kenny Bania",
  "Sue Ellen Mischke",
  "Uncle Leo",
  "Ruthie Cohen",
  "Jacopo Peterman",
  "Tim Whatley",
  "Lloyd Braun"
]

representatives =
  Enum.map(seinfeld_names, fn name ->
    Helpdesk.Support.Representative
    |> Ash.Changeset.for_create(:create, %{name: name})
    |> Helpdesk.Support.create!()
  end)

dbg(representatives)

issue_subjects = [
  "Coffee stain on favorite shirt",
  "Can't find car in parking garage",
  "Soup Nazi's soup didn't taste right",
  "Can't remember where I parked my car",
  "Kramer keeps borrowing things without asking",
  "Lost my apartment key",
  "George's double-dipping etiquette",
  "Muffin tops vs. whole muffins debate",
  "Elaine's terrible dance moves",
  "Kramer's bizarre business ideas",
  "Jerry's girlfriend looks too much like his ex",
  "Borrowed umbrella got destroyed",
  "Kramer's crazy hairdo ruined by rain",
  "Serenity Now! stress relief technique not working",
  "Sneezed without covering mouth in public",
  "Misplaced my glasses",
  "Can't find a clean shirt with a good collar",
  "George's failed attempts at looking busy at work",
  "Jerry's favorite pen ran out of ink",
  "Soup too hot to eat",
  "Newman's annoying habits",
  "Elaine's boyfriend's terrible wardrobe",
  "Kramer's loud late-night parties",
  "Can't decide which cereal to buy",
  "Lost TV remote control",
  "George's failed attempts to impress women",
  "Elaine's awkward social encounters",
  "Kramer's wild stories",
  "Jerry's annoying neighbor keeps asking for favors",
  "Stubbed my toe on coffee table",
  "Can't find matching socks",
  "George's obsession with food",
  "Kramer's strange fashion choices",
  "Elaine's struggle to find a decent man",
  "Jerry's stand-up comedy performance bombed",
  "Lost my favorite pen",
  "Kramer's failed attempts at acting",
  "Can't get a reservation at a fancy restaurant",
  "George's failed job interviews",
  "Elaine's tangled headphone wires",
  "Jerry's dating mishaps",
  "Kramer's weird eating habits",
  "Can't get rid of bad smell in apartment",
  "Lost my glasses in the ocean",
  "George's ongoing battle with his parents",
  "Elaine's constant bad luck",
  "Jerry's miscommunication with girlfriend",
  "Kramer's misguided attempts at helping friends",
  "Can't find my favorite sneakers",
  "George's obsession with bathroom habits",
  "Elaine's struggle to find a good contraceptive",
  "Jerry's uncomfortable seating arrangements",
  "Kramer's bizarre medical conditions",
  "Can't get rid of squeaky shoes",
  "George's failed attempts to break up with someone",
  "Elaine's frustration with men's fashion",
  "Jerry's failed attempts at being romantic",
  "Kramer's wild party planning",
  "Can't find my TV remote",
  "George's fear of commitment",
  "Elaine's terrible taste in men",
  "Jerry's struggle to remember names",
  "Kramer's unusual pet choices",
  "Can't find my car keys",
  "George's paranoia",
  "Elaine's run-ins with crazy exes",
  "Jerry's struggle to keep a clean apartment",
  "Kramer's bizarre inventions",
  "Can't get a table at popular restaurant",
  "George's social awkwardness",
  "Elaine's annoying co-worker",
  "Jerry's uncomfortable family gatherings",
  "Kramer's botched attempts at cooking",
  "Can't find my favorite book",
  "George's bad luck",
  "Elaine's ongoing feud with Soup Nazi",
  "Jerry's awkward encounters with neighbors",
  "Kramer's bizarre beauty routine",
  "Can't get rid of noisy neighbors",
  "George's obsession with the perfect alias",
  "Elaine's fashion disasters",
  "Jerry's awkward encounters with exes",
  "Kramer's misadventures with pets",
  "Can't find my favorite mug",
  "George's struggle to find a good hiding spot",
  "Elaine's attempts at being assertive",
  "Jerry's awkward gym experiences",
  "Kramer's wild driving habits",
  "Can't get a refund for a bad product",
  "George's run-ins with his boss",
  "Elaine's failed attempts at baking",
  "Jerry's bad hair day",
  "Kramer's wild hair mishaps",
  "Can't find my umbrella on a rainy day",
  "George's obsession with cheap deals",
  "Elaine's constant mishaps at work",
  "Jerry's arguments with friends over trivial matters",
  "Kramer's peculiar sleep habits",
  "Can't find my favorite DVD",
  "George's constant complaining",
  "Elaine's run-ins with annoying neighbors",
  "Jerry's frustration with technology",
  "Kramer's bizarre gardening experiments",
  "Can't get a refund for a bad haircut",
  "George's failed attempts at being suave",
  "Elaine's struggles with public transportation",
  "Jerry's awkward encounters at the gym",
  "Kramer's wild party crashing adventures",
  "Can't find my favorite hat",
  "George's obsession with cleanliness",
  "Elaine's ongoing feud with the mailman",
  "Jerry's annoying acquaintance",
  "Kramer's misguided attempts at fixing things",
  "Can't find my favorite tie",
  "George's paranoid theories",
  "Elaine's mishaps with online dating",
  "Jerry's arguments with cable company",
  "Kramer's bizarre culinary experiments",
  "Can't get a refund for spoiled food",
  "George's failed attempts to impress his parents",
  "Elaine's struggle to find good coffee",
  "Jerry's awkward encounters with strangers",
  "Kramer's strange fashion trends",
  "Can't find my favorite sunglasses",
  "George's obsession with bathroom privacy",
  "Elaine's ongoing drama with boyfriends",
  "Jerry's disagreement with neighbors",
  "Kramer's unusual exercise routines",
  "Can't get rid of a bad smell in apartment",
  "George's constant need for validation",
  "Elaine's battle with noisy roommates",
  "Jerry's fear of germs",
  "Kramer's bizarre diet choices",
  "Can't find my favorite CD",
  "George's awkward social interactions",
  "Elaine's awkward encounters with ex-boyfriends",
  "Jerry's frustrations with online shopping",
  "Kramer's quirky cleaning routines",
  "Can't get a refund for a defective product",
  "George's obsession with job security",
  "Elaine's struggle to find the perfect gift",
  "Jerry's arguments with restaurant staff",
  "Kramer's oddball fitness regime",
  "Can't find my favorite magazine",
  "George's paranoia about food poisoning",
  "Elaine's ongoing feud with her landlord",
  "Jerry's struggles with fashion trends",
  "Kramer's bizarre beauty treatments",
  "Can't get rid of a noisy neighbor",
  "George's failed attempts at lying",
  "Elaine's bad luck with roommates",
  "Jerry's frustration with traffic",
  "Kramer's wild party planning ideas"
]

tickets =
  Enum.map(issue_subjects, fn name ->
    status = Enum.random([:open, :closed])

    Helpdesk.Support.Ticket
    |> Ash.Changeset.for_create(:create, %{
      subject: name,
      status: status,
      representative_id: Enum.random(representatives).id
    })
    |> Helpdesk.Support.create!()
  end)

dbg(tickets)
